# https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz

name: CRC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
env:
  ON_DEMAND_DEBUG_PODS: false
  TERM: xterm-color

jobs:
  smoke-tests:
    name: Run Smoke Tests Against OpenShift Local
    runs-on: macos-latest
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/Users/runner/.kube/config'

    steps:
      - name: Download brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install the oc binaries
        run: |
          brew install openshift-cli
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: check if CRC_PULL_SECRET exists
        env: 
          super_secret: ${{ secrets.CRC_PULL_SECRET }}
        if: ${{ env.super_secret == '' }}
        run: 'echo the secret \"CRC_PULL_SECRET\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it'

      - name: Write the pull secret to json file
        run: |
          echo $CRC_PULL_SECRET > temp-ps.json
        env:
          CRC_PULL_SECRET: ${{ secrets.CRC_PULL_SECRET }}
        shell: bash

      # Create a OpenShift Local Cluster for testing
      - name: Curl the CRC binary
        run: |
          wget -O crc-macos-installer.pkg https://storage.googleapis.com/crc-bundle-github-ci/crc-microshift/crc-macos-installer.pkg
      - name: Install CRC
        run: |
          sudo installer -pkg crc-macos-installer.pkg -target /
      - name: Set Preset
        run: |
          crc config set preset microshift; sleep 60
      - name: Run CRC Setup
        run: |
          crc setup; sleep 60
      - name: Run CRC Start
        run: |          
          crc start --pull-secret-file temp-ps.json --log-level debug
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: use the podman env from microshift preset
        run: |
          eval $(crc podman-env --root) && podman build -t quay.io/praveenkumar/myserver:v1 -f Containerfile .
      - name: Create resource (namespace/pod/service)
        run: |
          oc --kubeconfig ${HOME}/.crc/machines/crc/kubeconfig apply -f kubernetes/deploy.yaml
      - name: Create the route
        run: |
          oc --kubeconfig ${HOME}/.crc/machines/crc/kubeconfig expose service myserver -n demo
      - name: Get all the pods
        run: |          
          oc --kubeconfig ${HOME}/.crc/machines/crc/kubeconfig get pods -A
      - name: get the routes
        run: |
          oc --kubeconfig ${HOME}/.crc/machines/crc/kubeconfig get routes -n demo
      - name: access route using curl
        run: |
          curl -Ik myserver-demo.apps.crc.testing
